### ISSUE TITLE
Avoid TOCTOU for container verification

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#243]
There is a race / Time-Of-Check-Time-Of-Use attack on container verification. When verifying a container `name:tag`, the verification may pass but the image that is pulled could have been changeed between the verification and the pull. We need to decide what to do about it:
1. Force users to pass container images by `@sha256:xxx`. 
  - Pro: This is the most secure option
  - Cons: 
     - We need to document which command for users to use (not a big deal I suppose), maybe with different tools (crane / docker / etc)
     - Not supported for GCB at the moment because GCB does not support storing the provenance along side the container. This will be supported in the future, though. 
2. Let users pass mutable tag
  - Pros: easy for users. 
  - Cons: 
     - We need to provide a way for them to get the digest. We could print it to stdin (`slsa-verifier ... | docker run`). Or we could document how to use `jq` to grab the digest from provenance, assuming there is a single subject in the provenance: `slsa-verifier ... -print-provenance | jq .. | docker run`. If there are multiple subjects, the only viable solution is to print it to stdout.
     - There is a risk users forget to use the verified sha256. We can add this to our documentation, and also print a warning in stdout with a link to the documentation to avoid the attack.

Thoughts?

/cc @asraa @ianlewis

**Comment by ianlewis** [comment]
> 1. Force users to pass container images by `@sha256:xxx`.

This is what the slsa-github-generator generic container workflow is [currently doing](https://github.com/slsa-framework/slsa-github-generator/blob/b0db1514cfb447dd016190b974ebe6e69ff59dcc/internal/builders/container/README.md#getting-started). However it [splits the image name and tag](https://github.com/slsa-framework/slsa-github-generator/blob/b0db1514cfb447dd016190b974ebe6e69ff59dcc/.github/workflows/generator_container_slsa3.yml#L29-L36) into separate inputs in order to make it clear that this is necessary and ease validation.

Unfortunately the workflow wouldn't be able to use tags because we don't have the luxury of being able to specify piped commands to get the digest and avoid a TOCTOU. So if we went with option 2 for the verifier, in the case of the workflow you would build the image, use the sha to generate the SLSA and then verify with the tag. This might be a bit disjointed as a user experience.

However, In the case of the verifier I suppose option 2 would make sense for generators that use tags (like GCB currently). So by making one method easier, others might become worse UX 😕

Overall I support using option 1. It's more secure and you generally have to do this anyway with tools like `cosign`. But I understand the dilemma with regard to GCB.

**Comment by ianlewis** [comment]
> I thought cosign does not force users to pass an immutable image, does it?

`cosign` will technically let you use the tag, but it assumes the image is already in the registry when you run `cosign attest` so the same TOCTOU occurs at build time too. The image tag could be modified between when the image is built and when `cosign attest` is run. So you need to use the digest.

Note: I think there is a `--local` option which gives `cosign` the ability to act on a local version of the image but in the case of the workflow, image build and provenance generation happen on separate job steps and thus separate VMs. For the other generic workflow we can upload a binary artifact to the workflow run (and pass the sha256sum for verification as as an input), but this isn't an option for container images.

**Comment by asraa** [comment]
> Option 1 is fine with me to start with: we can always relax this requirement later if we wanted, whereas the other way around would be a breaking change.

+1. There is also no benefit to passing a tag besides compatibility with existing commands (maybe, which also might be susceptible to the same issues). We don't do any tag verification. 

I'm not sure I understand the GCB issue of not having the provenance alongside?

**Comment by laurentsimon** [comment]
actually you're right, Asra. We can still force users to use a `@sha256:xxx` container image to GCB for verification. Sorry I got confused. Let's start with option 1 then.

**Comment by laurentsimon** [comment]
This is fixed. Before merging this PR, I wanted to ask about local images, ie those already pulled. Since they are local, they don't necessarily need to be pinned by hash. It's still dangerous. Bit I wanted to have your thoughts on the risk. In a multi-user environment, this could be risky... if the docker daemon does not differentiate between users. I'm pretty sure it does.

So it seems the risk is mostly a mistake by a developer, verifying then pulling a more recent version. This could also happen if the verifier and downloader are different daemon on the machine.

Any other thoughts?

**Comment by laurentsimon** [comment]
Let's close.
