### ISSUE TITLE
Possible code duplication

### ISSUE THREAD

**Issue by lukehinds** [slsa-framework/slsa-verifier#377]
Was reading over the code and noticed the following:

https://github.com/slsa-framework/slsa-verifier/blob/798db79f54ede97ddd9a925fe7a7df39b496b7b7/verifiers/internal/gcb/provenance.go#L413-L430

There maybe some logic in the duplication, if so this is invalid, but I thought it worth raising in case it's a mistake and causes some edge case bug.

**Comment by ianlewis** [comment]
@lukehinds Did you mean to close this? Even if the code is valid for some reason it's a bit unintuitive so perhaps could use a comment.

**Comment by ianlewis** [comment]
It looks like where `decodeSignature` is used is also strange as it returns an `[]error` but that slice isn't checked.

https://github.com/slsa-framework/slsa-verifier/blob/798db79f54ede97ddd9a925fe7a7df39b496b7b7/verifiers/internal/gcb/provenance.go#L463-L467

**Comment by ianlewis** [comment]
I'll reopen since this looks strange to me.

/cc @laurentsimon since it looks like this was added in #251

**Comment by lukehinds** [comment]
> @lukehinds Did you mean to close this? Even if the code is valid for some reason it's a bit unintuitive so perhaps could use a comment.

I did, but perhaps it does merit some attention. My eyes did not make out URLEncoding and StdEncoding as different.

**Comment by laurentsimon** [comment]
Let me explain. We try both encoding because, when verifying GCB provenance, it sometimes failed due to an encoding issue. So I added this "redundant-looking" base64 decoding to avoid the problem. I agree it's worth adding a comment, which I should have done :/

`decodeSIgnature()` is called https://github.com/slsa-framework/slsa-verifier/blob/798db79f54ede97ddd9a925fe7a7df39b496b7b7/verifiers/internal/gcb/provenance.go#L463
and appended to a list of errors https://github.com/slsa-framework/slsa-verifier/blob/798db79f54ede97ddd9a925fe7a7df39b496b7b7/verifiers/internal/gcb/provenance.go#L465

If the loop (which iterates over all the signatures in the envelope) fails, we return all the errors we encountered https://github.com/slsa-framework/slsa-verifier/blob/798db79f54ede97ddd9a925fe7a7df39b496b7b7/verifiers/internal/gcb/provenance.go#L487, which propagates to the caller https://github.com/slsa-framework/slsa-verifier/blob/798db79f54ede97ddd9a925fe7a7df39b496b7b7/verifiers/internal/gcb/provenance.go#L500 as a single `error`. 

The `verifySignature()` originates from https://github.com/slsa-framework/slsa-verifier/blob/798db79f54ede97ddd9a925fe7a7df39b496b7b7/verifiers/internal/gcb/verifier.go#L54 and it would fail at this line.

**Comment by ianlewis** [comment]
@lukehinds 

> I did, but perhaps it does merit some attention. My eyes did not make out URLEncoding and StdEncoding as different.

tbh, you're in good company. I didn't see that either... Yeah, probably a comment would have been good to make it clearer.

@laurentsimon

> It looks like where `decodeSignature` is used is also strange as it returns an `[]error` but that slice isn't checked.
> 
> https://github.com/slsa-framework/slsa-verifier/blob/798db79f54ede97ddd9a925fe7a7df39b496b7b7/verifiers/internal/gcb/provenance.go#L463-L467

I think you want the error checking line to be
```golang
if len(es) != 0 {
```
perhaps?
