### ISSUE TITLE
invalid DSSE envelope payload: invalid character 'i' looking for beginning of value

### ISSUE THREAD

**Issue by irsl** [slsa-framework/slsa-verifier#488]
Trying to verify provenance metadata generated by GCB via Github trigger (but I also encounter the same error if I upload the build package to GCB myself).

```
$ IMAGE='us-west2-docker.pkg.dev/imre-test/quickstart-docker-repo/quickstart-image:v41@sha256:41cb4b5e32e417b86c2b2229d0581b72f7dffd1cc6b0e586ab2cefdb7a527529'
$ ./slsa-verifier-linux-amd64 verify-image "$IMAGE"   --provenance-path provenance-github.yaml --builder-id=https://cloudbuild.googleapis.com/GoogleHostedWorker --source-uri github.com/irsl/gcb-tests
invalid DSSE envelope payload: invalid character 'i' looking for beginning of value
```

slsa-verifier is v2.0.1.
The provenance file: https://gist.github.com/irsl/2eaca58f22e0a2d5e9a675f9cc4aef70

The issue seems similar to https://github.com/slsa-framework/slsa-verifier/issues/267

Did I make a mistake somewhere or has the structure changed? Is there a workaround?

**Comment by ianlewis** [comment]
Hi @irsl! Thanks for the report.

Currently I think we only support the provenance in json format so that's the error you're getting I think. You can use the [`gcloud` command shown in the `README.md`](https://github.com/slsa-framework/slsa-verifier#containers-1) to download the provenance in JSON format.

**Comment by irsl** [comment]
Ah, works like a charm :) Thanks for the hint!
