### ISSUE TITLE
Support multiple artifact

### ISSUE THREAD

**Issue by laurentsimon** [slsa-framework/slsa-verifier#91]
The generic provenance can have multiple artifacts/subject. We may want to support verification "in bulk", where a user passes a folder as argument, and we verify all artifacts.

The verifier already supports `--artifact-path`, so this feature won't change the CLI.

An alternative would be to support multiple `--artifact-path` options...

I think using a folder is simpler. Wdut?

**Comment by laurentsimon** [comment]
@ianlewis commented on a duplicate issue:
I'm not sure if this is particularly high priority since

1. Provenance is somewhat likely to be created 1:1 with artifacts.
2. I think users will always be verifying a subset of the artifacts listed in provenance.
3. Feedback to the user becomes more complicated. Which artifact was the one that failed? Is a simple human readable error message sufficient?

**Comment by laurentsimon** [comment]
Point 3 is the hard part.

**Comment by mihaimaruseac** [comment]
In #174 we have the scenario where a provenance file contains multiple artifacts, yet a single one is passed in the command line.

I'm thinking we have the following scenarios:

1. provenance is for one artifact, user passes one artifact
1. provenance if for one artifact, user passes multiple artifacts

**Comment by mihaimaruseac** [comment]
In #174 we have the scenario where a provenance file contains multiple artifacts, yet a single one is passed in the command line.

I'm thinking we have the following scenarios:

1. provenance is for one artifact, user passes one artifact. This is what we do now, validating that the artifact is covered by the provenance
1. provenance is for multiple artifacts, user passes just one artifact. Accidentally, this is what we do now, treating it as similar to as if the provenance is just for the artifact that the user passed in (as is the case in #174 ). If the argument artifact is not included in the provenance we fail the validation (as we should)
1. provenance if for multiple artifacts, user passes multiple artifacts. Not handled, discussing below.
1. provenance if for one artifact, user passes multiple artifacts. Corner case of the above

I think we can generalize the above to requiring a single provenance path and source URI (as we do now) and one or more artifacts. Validation passes for all artifacts if all artifacts are included in the provenance, all generated from the same build. If at least one artifact fails, we print the fail message and then print the artifact that fails and one of the error cases:

* artifact is included in `subject` but hash is not matching
* artifact is not included in `subject`, not covered by the provenance

Currently (after #231), there is no more `--artifact-path` option, artifacts are just positional arguments, but they have to be files (and only one argument!). We can relax the restriction to just one argument, we can treat directory paths as globbing to get all artifacts within the directory (though maybe it would be better to explicitly list the artifacts instead of globbing a directory).

WDYT? I have a few cycles to look into this now, I'll probably send a PR just for discussion on how this looks

**Comment by laurentsimon** [comment]
Do you know if it's possible to use multiple path: `slsa-verifier verify-artifact <path1> <path2>`?
For directories, like you say, we could list all the files and use them all during verification. Do you think it should be `slsa-verifier verify-artifact path/to/dir/*` or simply `slsa-verifier verify-artifact path/to/dir`?

**Comment by mihaimaruseac** [comment]
We can definitely use multiple paths, currently the blocker is https://github.com/slsa-framework/slsa-verifier/blob/82cb42fb2084c5b9b2d3707d46e1641ccaaab267/cli/slsa-verifier/verify.go#L37-L40

Once the check is removed, we can pass multiple arguments, but need to update the logic to handle them. If I read the code correctly, we currently only take the first one of them: https://github.com/slsa-framework/slsa-verifier/blob/82cb42fb2084c5b9b2d3707d46e1641ccaaab267/cli/slsa-verifier/verify/verify_artifact.go#L43

I would prefer the option with `/*` instead of `path/to/dir` as it would make it explicit that we only want files.

**Comment by laurentsimon** [comment]
Got it, thanks. These changes look useful and should not break backward compatibility. When we have a slsa-verifier as a service, we'll probably need to enforce a max length to avoid DoS. For the CLI, LGTM.

@asraa @ianlewis any thoughts?

**Comment by mihaimaruseac** [comment]
Turns out the changes are even simpler, see #419

**Comment by laurentsimon** [comment]
Let's also add some e2e test for this feature in slsa-framework/example-package. One test should be enough.
